# Generated by Django 5.1.7 on 2025-09-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire_builder', '0002_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
