# Generated by Django 5.1.7 on 2025-10-19 05:21

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire_builder', '0003_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEngineConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=255)),
                ('system_prompt', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'AI Engine Configuration',
                'verbose_name_plural': 'AI Engine Configurations',
            },
        ),
    ]
