# Generated by Django 5.1.7 on 2025-11-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire_builder', '0005_update_api_key_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aiengineconfiguration',
            old_name='api_key',
            new_name='_api_key',
        ),
        migrations.AddField(
            model_name='aiengineconfiguration',
            name='modification_prompt',
            field=models.TextField(blank=True),
        ),
    ]
