// This file is auto-generated by @hey-api/openapi-ts

export const $Login = {
  type: "object",
  properties: {
    email: {
      type: "string",
      format: "email",
    },
    password: {
      type: "string",
      writeOnly: true,
    },
  },
  required: ["email", "password"],
} as const;

export const $Logout = {
  type: "object",
  properties: {
    detail: {
      type: "string",
      readOnly: true,
    },
  },
  required: ["detail"],
} as const;

export const $Message = {
  type: "object",
  properties: {
    message: {
      type: "string",
    },
  },
  required: ["message"],
} as const;

export const $PaginatedUserList = {
  type: "object",
  required: ["count", "results"],
  properties: {
    count: {
      type: "integer",
      example: 123,
    },
    next: {
      type: "string",
      nullable: true,
      format: "uri",
      example: "http://api.example.org/accounts/?offset=400&limit=100",
    },
    previous: {
      type: "string",
      nullable: true,
      format: "uri",
      example: "http://api.example.org/accounts/?offset=200&limit=100",
    },
    results: {
      type: "array",
      items: {
        $ref: "#/components/schemas/User",
      },
    },
  },
} as const;

export const $PatchedUser = {
  type: "object",
  properties: {
    id: {
      type: "integer",
      readOnly: true,
    },
    email: {
      type: "string",
      format: "email",
      maxLength: 255,
    },
    is_active: {
      type: "boolean",
      description:
        "Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
    },
    is_staff: {
      type: "boolean",
      description: "Designates whether the user can log into this admin site.",
    },
    is_superuser: {
      type: "boolean",
      title: "Superuser status",
      description:
        "Designates that this user has all permissions without explicitly assigning them.",
    },
    created: {
      type: "string",
      format: "date-time",
      readOnly: true,
    },
    modified: {
      type: "string",
      format: "date-time",
      readOnly: true,
    },
    last_login: {
      type: "string",
      format: "date-time",
      nullable: true,
    },
  },
} as const;

export const $Question = {
  type: "object",
  properties: {
    value: {
      type: "string",
      maxLength: 255,
    },
    order: {
      type: "integer",
      maximum: 2147483647,
      minimum: -2147483648,
    },
    answers: {
      type: "array",
      items: {
        $ref: "#/components/schemas/QuestionAnswer",
      },
    },
  },
  required: ["answers", "order", "value"],
} as const;

export const $QuestionAnswer = {
  type: "object",
  properties: {
    value: {
      type: "string",
      maxLength: 255,
    },
    order: {
      type: "integer",
      maximum: 2147483647,
      minimum: -2147483648,
    },
    input: {
      type: "string",
      maxLength: 255,
    },
  },
  required: ["input", "order", "value"],
} as const;

export const $Questionnaire = {
  type: "object",
  properties: {
    name: {
      type: "string",
      maxLength: 255,
    },
    status: {
      type: "string",
      maxLength: 255,
    },
    questions: {
      type: "array",
      items: {
        $ref: "#/components/schemas/Question",
      },
    },
  },
  required: ["name", "questions", "status"],
} as const;

export const $User = {
  type: "object",
  properties: {
    id: {
      type: "integer",
      readOnly: true,
    },
    email: {
      type: "string",
      format: "email",
      maxLength: 255,
    },
    is_active: {
      type: "boolean",
      description:
        "Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
    },
    is_staff: {
      type: "boolean",
      description: "Designates whether the user can log into this admin site.",
    },
    is_superuser: {
      type: "boolean",
      title: "Superuser status",
      description:
        "Designates that this user has all permissions without explicitly assigning them.",
    },
    created: {
      type: "string",
      format: "date-time",
      readOnly: true,
    },
    modified: {
      type: "string",
      format: "date-time",
      readOnly: true,
    },
    last_login: {
      type: "string",
      format: "date-time",
      nullable: true,
    },
  },
  required: ["created", "email", "id", "modified"],
} as const;
