# Generated by Django 5.1.7 on 2025-09-08 01:46

from django.db import migrations
from django.contrib.auth import get_user_model
import os


def create_superuser(apps, schema_editor):
    User = get_user_model()
    
    # Get superuser credentials from environment variables
    admin_email = os.environ.get('ADMIN_EMAIL', 'admin@example.com')
    admin_password = os.environ.get('ADMIN_PASSWORD', 'admin123')
    
    # Only create if superuser doesn't exist
    if not User.objects.filter(email=admin_email).exists():
        User.objects.create_superuser(
            email=admin_email,
            password=admin_password
        )
        print(f"Created superuser: {admin_email}")


def reverse_create_superuser(apps, schema_editor):
    User = get_user_model()
    admin_email = os.environ.get('ADMIN_EMAIL', 'admin@example.com')
    User.objects.filter(email=admin_email).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_admininvite'),
    ]

    operations = [
        migrations.RunPython(create_superuser, reverse_create_superuser),
    ]
